#!/bin/bash
#
# configure nginx
#
# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
echo "This script must be run as root" 1>&2
    exit 1
fi

source /etc/default/app

add_generic_conf() {
    # function should be called with arguments:
    # $1 - conf_file
    # $2 - project_name

    cat <<EOF >$1
server {
    listen 80 default deferred; # for Linux
    client_max_body_size 4G;
    server_name _;

    # ~2 seconds is often enough for most folks to parse HTML/CSS and
    # retrieve needed images/icons/frames, connections are cheap in
    # nginx so increasing this is generally safe...
    keepalive_timeout 5;

    root /opt/app/$2/current/public;

    access_log /var/log/nginx/$2-access.log;
    error_log /var/log/nginx/$2-error.log;

    # Prefer to serve static files directly from nginx to avoid unnecessary
    # data copies from the application server.
    #
    # try_files directive appeared in in nginx 0.7.27 and has stabilized
    # over time.  Older versions of nginx (e.g. 0.6.x) requires
    # "if (!-f \$request_filename)" which was less efficient:
    # http://bogomips.org/unicorn.git/tree/examples/nginx.conf?id=v3.3.1#n127
    try_files \$uri/index.html \$uri.html \$uri @app;

    location @app {
      # an HTTP header important enough to have its own Wikipedia entry:
      #   http://en.wikipedia.org/wiki/X-Forwarded-For
      proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;

      # enable this if you forward HTTPS traffic to unicorn,
      # this helps Rack set the proper URL scheme for doing redirects:
      # proxy_set_header X-Forwarded-Proto \$scheme;

      # pass the Host: header from the client right along so redirects
      # can be set properly within the Rack application
      proxy_set_header Host \$http_host;

      # we don't want nginx trying to do something clever with
      # redirects, we set the Host: header above already.
      proxy_redirect off;

      # set "proxy_buffering off" *only* for Rainbows! when doing
      # Comet/long-poll/streaming.  It's also safe to set if you're using
      # only serving fast clients with Unicorn + nginx, but not slow
      # clients.  You normally want nginx to buffer responses to slow
      # clients, even with Rails 3.1 streaming because otherwise a slow
      # client can become a bottleneck of Unicorn.
      #
      # The Rack application may also set "X-Accel-Buffering (yes|no)"
      # in the response headers do disable/enable buffering on a
      # per-response basis.
      # proxy_buffering off;

      proxy_pass http://app_server;
    }

    # Rails error pages
    error_page 500 502 503 504 /500.html;
    location = /500.html {
      root /opt/app/$2/current/public;
    }
}
EOF

}

NGINX_RAILS_CONF_FILE=/etc/nginx/conf.d/rails.conf

usage() {
  echo ""
  echo "Usage: $0 tech_stack"
  exit 1
}

if [ -z "$1" ]; then
  usage
fi

tech_stack=$1

mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.back
if [ $tech_stack == "rails" ]; then
   add_generic_conf $NGINX_RAILS_CONF_FILE $PROJECT_NAME
fi

