#!/bin/sh

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
echo "This script must be run as root" 1>&2
    exit 1
fi

# Load configuration
. /etc/default/app

# Export access key ID and secret for cli53
export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY

# Use command line scripts to get public hostname
PUBLIC_HOSTNAME=$(/opt/aws/bin/ec2-metadata | grep 'public-hostname:' | cut -d ' ' -f 2)

# Create a new CNAME record on Route 53, replacing the old entry if nessesary
/usr/local/bin/cli53 list "$ZONE" 2>1 | grep "$ENVIRONMENT_NAME.$PROJECT_NAME"
if [ "$?" -eq "0" ]; then
  echo "Updating an existing DNS CNAME"
  /usr/local/bin/cli53 rrcreate "$ZONE" "$ENVIRONMENT_NAME.$PROJECT_NAME" CNAME "$PUBLIC_HOSTNAME" --replace --ttl "$TTL"
fi

